services:
  - type: web
    name: ignitex-hackrx-doc-api
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
